import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { ShieldCheck, Menu, X, LogOut, WifiOff, Bell, UserRound, Home, AlertTriangle, Users, Package, MapPinned, Database, Gauge, RefreshCw, Settings, Activity, BarChart3 } from 'lucide-react';
import { useAuth } from './auth';
import { useOnline } from './hooks';
import { db } from './db';
import { syncNow } from './sync';
export const Brand = ({ light = false }) => _jsxs(Link, { className: 'brand ' + (light ? 'lightbrand' : ''), to: "/", children: [_jsx("i", { children: _jsx(ShieldCheck, { size: 19 }) }), _jsx("span", { children: "RESCUE" }), "GRID"] });
export function Status() { const online = useOnline(); const [state, setState] = useState('ONLINE'); const [p, setP] = useState(0); useEffect(() => { const f = async () => { const rows = await db.pending.toArray(); setP(rows.filter(x => ['pending', 'failed', 'conflict'].includes(x.status)).length); setState(rows.some(x => x.status === 'conflict') ? 'CONFLICT' : rows.some(x => x.status === 'syncing') ? 'SYNCING' : rows.some(x => x.status === 'failed') ? 'ERROR' : online ? (rows.some(x => x.status === 'pending') ? 'SYNCING' : 'SYNCED') : 'OFFLINE'); }; f(); const i = setInterval(f, 1000); return () => clearInterval(i); }, [online]); return _jsxs("div", { className: 'status ' + (['OFFLINE', 'CONFLICT', 'ERROR'].includes(state) ? 'off' : ''), children: [_jsx("b", {}), state, p > 0 && _jsxs("button", { onClick: () => syncNow(), children: [_jsx(RefreshCw, { size: 12 }), p] })] }); }
const nav = { community: [['Dashboard', '/dashboard/community', Home], ['Report Emergency', '/dashboard/community/report', AlertTriangle], ['Emergency Map', '/dashboard/community/map', MapPinned], ['My Reports', '/dashboard/community/reports', Database], ['Nearby Help', '/dashboard/community/help', Users], ['Safety Information', '/dashboard/community/safety', ShieldCheck], ['Profile', '/dashboard/community/profile', UserRound], ['Settings', '/dashboard/community/settings', Settings]], rescue: [['Dashboard', '/dashboard/rescue', Gauge], ['Victims', '/dashboard/rescue/victims', Users], ['Incidents', '/dashboard/rescue/incidents', AlertTriangle], ['Resources', '/dashboard/rescue/resources', Package], ['Emergency Map', '/dashboard/rescue/map', MapPinned], ['Sync Center', '/dashboard/rescue/sync', RefreshCw], ['Activity', '/dashboard/rescue/activity', Activity], ['Settings', '/dashboard/rescue/settings', Settings]], admin: [['Overview', '/dashboard/admin', Gauge], ['Users', '/dashboard/admin/users', Users], ['Rescue Teams', '/dashboard/admin/teams', ShieldCheck], ['Incidents', '/dashboard/admin/incidents', AlertTriangle], ['Victims', '/dashboard/admin/victims', Users], ['Resources', '/dashboard/admin/resources', Package], ['Analytics', '/dashboard/admin/analytics', BarChart3], ['Emergency Map', '/dashboard/admin/map', MapPinned], ['Sync Monitoring', '/dashboard/admin/sync', RefreshCw], ['Settings', '/dashboard/admin/settings', Settings]] };
export function Shell({ role, title, children }) { const { user, logout } = useAuth(); const [open, setOpen] = useState(false); const go = useNavigate(); return _jsxs("div", { className: "shell", children: [_jsxs("aside", { className: open ? 'open' : '', children: [_jsxs("div", { className: "sidebrand", children: [_jsx(Brand, {}), _jsx("button", { onClick: () => setOpen(false), children: _jsx(X, {}) })] }), _jsxs("div", { className: "sideprofile", children: [_jsx("div", { className: "avatar", children: user?.full_name?.slice(0, 1).toUpperCase() || 'R' }), _jsxs("div", { children: [_jsx("b", { children: user?.full_name || 'RESCUEGRID User' }), _jsx("small", { children: role === 'community' ? 'Local User' : role === 'rescue' ? 'Security / Rescue Team' : 'Administrator' })] })] }), _jsx("small", { className: "navlabel", children: "OPERATIONS" }), _jsx("nav", { children: nav[role].map(([t, h, I]) => _jsxs(Link, { to: h, onClick: () => setOpen(false), children: [_jsx(I, { size: 16 }), t] }, h)) }), _jsxs("button", { className: "logout", onClick: () => { logout(); go('/'); }, children: [_jsx(LogOut, { size: 16 }), "Logout"] })] }), open && _jsx("div", { className: "scrim", onClick: () => setOpen(false) }), _jsxs("main", { children: [_jsxs("header", { children: [_jsx("button", { className: "menu", onClick: () => setOpen(true), children: _jsx(Menu, {}) }), _jsxs("div", { className: "pagehead", children: [_jsx("label", { children: "RESCUEGRID OPERATIONS" }), _jsx("h1", { children: title })] }), _jsxs("div", { className: "topright", children: [_jsx(Status, {}), _jsx(Bell, { size: 18 }), _jsxs("span", { children: [_jsx(UserRound, { size: 15 }), user?.full_name] })] })] }), children] })] }); }
export const Stat = ({ icon: I, label, value, hint, tone = 'blue' }) => _jsxs("div", { className: 'stat ' + tone, children: [_jsx("i", { children: _jsx(I, { size: 19 }) }), _jsxs("div", { children: [_jsx("small", { children: label }), _jsx("b", { children: value }), _jsx("em", { children: hint })] })] });
export const Offline = () => { const online = useOnline(); return online ? null : _jsxs("div", { className: "offline", children: [_jsx(WifiOff, { size: 15 }), _jsx("b", { children: "Offline mode" }), _jsx("span", { children: "Changes are stored locally and will synchronize when connectivity returns." })] }); };
