import {useEffect,useState,type ReactNode} from 'react';
import {Link,useNavigate,NavLink} from 'react-router-dom';
import {ShieldCheck,Menu,X,LogOut,Wifi,WifiOff,Bell,UserRound,Home,AlertTriangle,Users,Package,MapPinned,Database,Gauge,RefreshCw,Settings,Activity,BarChart3} from 'lucide-react';
import {useAuth} from './auth'; import {useOnline} from './hooks'; import {db} from './db'; import {syncNow} from './sync';
export const Brand=({light=false}:{light?:boolean})=><Link className={'brand '+(light?'lightbrand':'')} to="/"><i><ShieldCheck size={19}/></i><span>RESCUE</span>GRID</Link>;
export function Status(){const online=useOnline();const[state,setState]=useState('ONLINE');const[p,setP]=useState(0);useEffect(()=>{const f=async()=>{const rows=await db.pending.toArray();setP(rows.filter(x=>['pending','failed','conflict'].includes(x.status)).length);setState(rows.some(x=>x.status==='conflict')?'CONFLICT':rows.some(x=>x.status==='syncing')?'SYNCING':rows.some(x=>x.status==='failed')?'ERROR':online?(rows.some(x=>x.status==='pending')?'SYNCING':'SYNCED'):'OFFLINE')};f();const i=setInterval(f,1000);return()=>clearInterval(i)},[online]);return <div className={'status '+(['OFFLINE','CONFLICT','ERROR'].includes(state)?'off':'')}><b/>{state}{p>0&&<button onClick={()=>syncNow()}><RefreshCw size={12}/>{p}</button>}</div>}
const nav:any={community:[['Dashboard','/dashboard/community',Home],['Report Emergency','/dashboard/community/report',AlertTriangle],['Emergency Map','/dashboard/community/map',MapPinned],['My Reports','/dashboard/community/reports',Database],['Safety Information','/dashboard/community/safety',ShieldCheck],['Profile','/dashboard/community/profile',UserRound]],rescue:[['Dashboard','/dashboard/rescue',Gauge],['Victims','/dashboard/rescue/victims',Users],['Incidents','/dashboard/rescue/incidents',AlertTriangle],['Resources','/dashboard/rescue/resources',Package],['Emergency Map','/dashboard/rescue/map',MapPinned],['Sync Center','/dashboard/rescue/sync',RefreshCw],['Activity','/dashboard/rescue/activity',Activity]],admin:[['Overview','/dashboard/admin',Gauge],['Rescue Teams','/dashboard/admin/teams',ShieldCheck],['Incidents','/dashboard/admin/incidents',AlertTriangle],['Victims','/dashboard/admin/victims',Users],['Resources','/dashboard/admin/resources',Package],['Emergency Map','/dashboard/admin/map',MapPinned],['Sync Monitoring','/dashboard/admin/sync',RefreshCw],['Settings','/dashboard/admin/settings',Settings]]};
export function Shell({role,title,children}:{role:'community'|'rescue'|'admin';title:string;children:ReactNode}){const{user,logout}=useAuth();const[open,setOpen]=useState(false);const go=useNavigate();return <div className="shell"><aside className={open?'open':''}><div className="sidebrand"><Brand/><button onClick={()=>setOpen(false)}><X/></button></div><div className="sideprofile"><div className="avatar">{user?.full_name?.slice(0,1).toUpperCase()||'R'}</div><div><b>{user?.full_name||'RESCUEGRID User'}</b><small>{role==='community'?'Local User':role==='rescue'?'Security / Rescue Team':'Administrator'}</small></div></div><small className="navlabel">OPERATIONS</small><nav>{nav[role].map(([t,h,I]:any)=><NavLink key={h} to={h} onClick={()=>setOpen(false)} className={({isActive})=>isActive?'active':''}><I size={16}/>{t}</NavLink>)}</nav><button className="logout" onClick={()=>{logout();go('/')}}><LogOut size={16}/>Logout</button></aside>{open&&<div className="scrim" onClick={()=>setOpen(false)}/>}<main><header><button className="menu" onClick={()=>setOpen(true)}><Menu/></button><div className="pagehead"><label>RESCUEGRID OPERATIONS</label><h1>{title}</h1></div><div className="topright"><Status/><Bell size={18}/><span><UserRound size={15}/>{user?.full_name}</span></div></header>{children}</main></div>}
export const Stat=({icon:I,label,value,hint,tone='blue'}:any)=><div className={'stat '+tone}><i><I size={19}/></i><div><small>{label}</small><b>{value}</b><em>{hint}</em></div></div>;
export const Offline=()=>{const online=useOnline();return online?null:<div className="offline"><WifiOff size={15}/><b>Offline mode</b><span>Changes are stored locally and will synchronize when connectivity returns.</span></div>};
